name: Clang Format Check and Fix

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Load environment variables from .env
      run: |
        if [ -f .env ]; then
          echo "Loading environment variables from .env file"
          source .env
        fi
      shell: bash

    - name: Install clang-format
      run: sudo apt-get install clang-format

    - name: Run clang-format
      run: |
        FILES=$(find . -name "xxx*.c")
        if [ -n "$FILES" ]; then
          echo "$FILES" | xargs clang-format -i
        else
          echo "No files found to format"
        fi

    - name: Commit changes if any
      run: |
        if ! git diff --quiet; then
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"
          git add .
          git commit -m "Apply clang-format changes"
          git push
        fi
      env:
        GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
